language: node_js
node_js: '10'
branches:
  only:
  - master
script: npm run build
before_deploy:
  - cp out_patch/* out && touch out/.nojekyll
  - openssl aes-256-cbc -K $encrypted_d20f69a780d0_key -iv $encrypted_d20f69a780d0_iv -in deploy-key.json.enc -out deploy-key.json -d
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: "deploy-key.json"
  project: "wtfsiw"
