language: node_js
node_js: '12'
branches:
  only:
  - main
script: npm run build
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

before_deploy:
- openssl aes-256-cbc -K $encrypted_d20f69a780d0_key -iv $encrypted_d20f69a780d0_iv
  -in deploy-key.json.enc -out deploy-key.json -d
- sh install_gcloud.sh
- gcloud auth activate-service-account --key-file deploy-key.json
- mkdir data
- gsutil cp gs://wtfsiw-database/db.sqlite data/db.sqlite

# Yes, it installs gcloud twice. No, I can't  be bothered fixing it
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: deploy-key.json
  project: wtfsiw
  on: main
