name = "wtfsiw"
type = "javascript"
account_id = "58371b47d4ca0f32a2aabf9c50836c44"
compatibility_date = "2022-03-05"
workers_dev = true

[[kv_namespaces]]
binding = "storage"
preview_id = "9f8139775fc044dda406db9c3b86a9b2"
id = "eff3591587a14a5eaf64699b2297e407"

[build]
command="npm run build"
watch_dir="src"

[build.upload]
format = "modules"
dir = "./dist"
main = "./server.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[env.staging]
zone_id = "a8f970aee785a2eb4d51fa750636af25"
route = "next.wtfsiw.xyz/*"

[env.production]
zone_id = "a8f970aee785a2eb4d51fa750636af25"
route = "wtfsiw.xyz/*"
